#sudo: false
sudo: true
dist: trusty

language: python

python:
    - '2.7'
    - '3.4'

virtualenv:
  system_site_packages: true

cache: pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install python-pytest python3-pytest
  - sudo apt-get -y install python-pip python3-pip
  - sudo -H pip install -r requirements.txt
  - pip install pytest-cov

install:
  - sudo -H pip install .
  - sudo -H pip3 install .

script:
  - cd test/
  - pytest --cov updated

after_success:
  - bash <(curl -s https://codecov.io/bash)
