dist: trusty

language: python

python:
    - '2.7'
    - '3.4'

# <https://docs.travis-ci.com/user/languages/python/>
# > If you need to install Python packages, do it via pip and not apt.
before_install:
  - pip install pytest pytest-cov

install:
  - pip install -r requirements.txt
  - pip3 install -r requirements.txt
  - pip install .
  - pip3 install .

script:
  - cd test/
  - pytest --cov updated

after_success:
  - bash <(curl -s https://codecov.io/bash)
